name: Anvil package Github actions

on:
  push

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle

    - name: Verify changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: |
            server_code/**/*.py

    - name: Run pycodestyle check
      if: ${{ steps.changed-files-specific.outputs.any_changed == 'true' }}
      run: |
        pycodestyle --config=./config/pycodestyle.cfg ${{ steps.changed-files-specific.outputs.all_changed_files }}
        if [ $? -ne 0 ]; then
            exit 1
        else
            echo "Run pycodestyle check successfully"
        fi
